version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.15.1
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths:
            - dist
  deploy:
    machine:
      image: ubuntu-2004:current
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: docker build -t hhoao/ret-web-admin-setup .
      - run:
          command: |
            if [ ! -d ~/.docker ];
            then
              mkdir ~/.docker
            if
            cat > ~/.docker/config.json \<< EOF
            {
              'auths': {
                  'https://index.docker.io/v1/': {
                  'auth':'$DOCKER_AUTH',
                }
              }
            }
      - run: docker push hhoao/ret-web-admin-setup
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
